name: gupshop
description: The instant way to achieve all!

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  google_fonts: ^0.5.0+1
  flutter:
    sdk: flutter

  firebase_auth: ^0.16.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # Add the dependency for the Firebase Core Flutter SDK
  firebase_core: ^0.4.0+9

  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^5.0.14

  contacts_service: ^0.3.10
  cloud_functions:  0.4.1+6
  flutter_contact: any #verson ^0.5.3 is incompatible with geolocator:^5.3.1. Hence we change flutter_contact version to any
  permission_handler: ^5.0.0+hotfix.3
  twilio_programmable_video: 0.6.1
  provider: ^4.1.3
  cloud_firestore: ^0.13.7 #^0.12.9+5 version before . changed  because geoflutterfire was not compatible with this version
  device_info: '>=0.4.1+4 <2.0.0'
  video_player: ^0.10.9 #video player for bazaar profile
  enum_to_string: ^1.0.9
  wakelock: ^0.1.4
  recase: ^3.0.0
  native_device_orientation: ^0.3.0
  image_picker: ^0.6.5+2 #for adding advertisement on bazaar profile
  shared_preferences: ^0.5.7 #for checking if the user is logged in for the 1st time
  firebase_database: ^3.1.6
  firebase_storage: ^3.1.5 #for image  and video storage to cloud storage
  after_layout: ^1.0.7
  geolocator: ^5.3.0
  geocoder: ^0.2.1
  location: ^3.0.2
  async: ^2.4.0

  geoflutterfire: ^2.1.0 # for finding nearby

  flutter_svg: ^0.17.4

  flappy_search_bar: ^1.7.2 # for searching
  rxdart: ^0.23.1 #for using BehaviorSubject in indiviudalChat . PS: rxdart: ^0.24.1 gives conflict with some other dependency so used ^0.23.1
  flushbar: ^1.10.4 #for snackbar
  get: ^2.10.0 #for navigation

  image_cropper: ^1.2.2
  flutter_image_compress: ^0.6.8
  cached_network_image: ^2.2.0+1
  transparent_image: ^1.0.0 #for fade in image
  country_pickers: ^1.3.0
  country_code_picker: ^1.3.15
  timeago: ^2.0.26

  url_launcher: ^5.4.11
  flutter_linkify: ^3.1.3

  html: ^0.14.0+3
  http: ^0.12.2

  image_downloader: ^0.20.0
  zoomable_image: ^1.3.1
  dio: ^3.0.10

  photo_view: ^0.10.1 # 20/8/20
  great_circle_distance: ^1.0.1 # 25/8/20
  google_maps_flutter: ^0.5.30 # 25/8/20
  flutter_bloc: ^6.0.1 #25/8/20
  search_map_place:
    git: https://github.com/lzzy12/search_map_place.git
  gallery_saver: ^2.0.1

  thumbnails: ^1.0.1 # for video thumbnail
  video_thumbnail: ^0.2.2 # for video thumbnail

  firebase_performance: ^0.3.2 # for data gathering.. latest is 0.4.0.. but conflicting with firebase core.. so used the prior version
  proximity_hash: ^1.0.1 #for location_service.dart to create geoHash #26/9/20
  firebase_messaging: ^6.0.16 # for push notifications

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/milk.png
    - images/sampleImageForBazaar.jpeg
    - images/sampleProfilePicture.jpeg
    - images/kamwali.png
    - videos/LevenworthVideo.mp4
    - images/crying.png
    - images/ok-hand.png
    - images/so-so.png
    - images/backArrow.svg
    - images/backArrowBlackWhite.svg
    - images/camera1.svg
    - images/image2vector.svg
    - images/photoGallery.svg
    - images/backArrowColor.svg
    - images/done.svg
    - images/nextArrow.svg
    - images/stopHand.svg
    - images/userFace.svg
    - images/userFace.png
    - images/user.png
    - images/id.png
    - images/goodIdCard.png
    - images/transparent.jpeg
    - images/whiteBackground.png
    - images/advancedSearch.svg
    - images/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages