name: gupshop
description: The instant way to achieve all!

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  google_fonts: ^0.5.0+1
  flutter:
    sdk: flutter

  firebase_auth: ^0.16.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # Add the dependency for the Firebase Core Flutter SDK
  firebase_core: ^0.4.0+9

  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^5.0.14

  contacts_service: ^0.3.10
  flutter_contact: any #verson ^0.5.3 is incompatible with geolocator:^5.3.1. Hence we change flutter_contact version to any
  permission_handler: ^5.0.0+hotfix.3

  cloud_firestore: ^0.13.5 #^0.12.9+5 version before . changed  because geoflutterfire was not compatible with this version

  video_player: ^0.10.9 #video player for bazaar profile

  image_picker: ^0.6.5+2 #for adding advertisement on bazaar profile
  shared_preferences: ^0.5.7 #for checking if the user is logged in for the 1st time
  firebase_database: ^3.1.6
  firebase_storage: ^3.1.5 #for image  and video storage to cloud storage

  geolocator: ^5.3.0
  geocoder: ^0.2.1
  location: ^3.0.2
  async: ^2.4.0

  geoflutterfire: ^2.1.0 # for finding nearby

  flutter_svg: ^0.17.4

  flappy_search_bar: ^1.7.2 # for searching
  rxdart: ^0.23.1 #for using BehaviorSubject in indiviudalChat . PS: rxdart: ^0.24.1 gives conflict with some other dependency so used ^0.23.1
  flushbar: ^1.10.4 #for snackbar
  get: ^2.10.0 #for navigation

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/milk.png
    - images/sampleImageForBazaar.jpeg
    - images/sampleProfilePicture.jpeg
    - images/kamwali.png
    - videos/LevenworthVideo.mp4
    - images/crying.png
    - images/ok-hand.png
    - images/so-so.png
    - images/backArrow.svg
    - images/backArrowBlackWhite.svg
    - images/camera1.svg
    - images/image2vector.svg
    - images/photoGallery.svg
    - images/backArrowColor.svg
    - images/done.svg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages